### ISSUE TITLE
But in vae.py? 

### ISSUE THREAD

**Issue by erlebach** [miyosuda/disentangled_vae#1]
Hi, 

In routine get_batch_images, one finds the line: 

    x = shape.x
    y = shape.x

Surely, the second line should be

   y = shape.y 

If so, how would that affect the results presented in the corresponding paper? If "y=shape.x" is ok, why?

**Comment by miyosuda** [comment]
Ah sorry this is my mistake!

> y = shape.y

is correct!
I'll fix as you suggest, and train again to update the result.
(With this mistake, images are all located on diagonal line, and so the result is wrong.)

**Comment by miyosuda** [comment]
I fixed it and updated the result. Thanks! @erlebach
